# Generated by Django 5.0.7 on 2024-09-17 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=328)),
                ('description', models.TextField()),
                ('photo500_x_800', models.ImageField(blank=True, upload_to='PhotoFox')),
                ('photo800_x_533', models.ImageField(blank=True, upload_to='PhotoFox')),
                ('categorie', models.CharField(max_length=328)),
                ('auteur', models.CharField(blank=True, max_length=328)),
                ('date', models.DateField(auto_now_add=True)),
                ('contenuP1', models.TextField(blank=True, null=True)),
                ('contenuConclusion', models.TextField(blank=True, null=True)),
                ('contenuSitation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=328)),
                ('sousTitre', models.TextField()),
                ('photo', models.ImageField(upload_to='PhotoFox')),
                ('descriptionP1', models.TextField()),
                ('descriptionP2', models.TextField()),
                ('signature', models.ImageField(upload_to='PhotoFox')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=328)),
                ('cv', models.FileField(blank=True, null=True, upload_to='FilesFox')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=328)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(blank=True, upload_to='PhotoFox')),
                ('photo2', models.ImageField(blank=True, upload_to='PhotoFox')),
                ('photo3', models.ImageField(blank=True, upload_to='PhotoFox')),
                ('categorie', models.CharField(max_length=328)),
                ('sujet', models.CharField(blank=True, max_length=328)),
                ('date', models.DateField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('signature', models.ImageField(upload_to='PhotoFox')),
                ('cv', models.FileField(upload_to='FilesFox')),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoxApp.post')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoxApp.visiteur')),
            ],
        ),
    ]
