# Generated by Django 5.0.7 on 2024-09-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxApp', '0002_profile_fecebook_profile_github_profile_gmail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='photo1',
            new_name='photo1_800_x_550',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='photo2',
            new_name='photo2_800_x_550',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='photo3',
            new_name='photo3_800_x_550',
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('objet', models.CharField(blank=True, max_length=500, null=True)),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoxApp.visiteur')),
            ],
        ),
    ]
