# Generated by Django 5.1.1 on 2024-10-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoxApp', '0003_rename_photo1_project_photo1_800_x_550_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fecebook',
            new_name='facebook',
        ),
    ]
