# Generated by Django 5.1.1 on 2024-10-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxApp', '0004_rename_fecebook_profile_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('contenuP1', models.TextField(blank=True, null=True)),
                ('contenuConclusion', models.TextField(blank=True, null=True)),
                ('contenuSitation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
