# Generated by Django 5.1.1 on 2025-01-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoxApp', '0006_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='project',
            name='signature',
        ),
    ]
