# Generated by Django 5.1.1 on 2025-02-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxApp', '0007_remove_project_cv_remove_project_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenuP2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contenuP3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contenuP4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo500_x_800',
            field=models.ImageField(upload_to='PhotoFox'),
        ),
    ]
