# Generated by Django 5.1.1 on 2025-03-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxApp', '0008_post_contenup2_post_contenup3_post_contenup4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='article_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
